package ca.mcgill.ecse.climbsafe.javafx.fxml.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import ca.mcgill.ecse.climbsafe.controller.ExtraFeaturesController;
import javafx.event.ActionEvent;

public class ClimbingPathOperationsController {
	@FXML
	private Button addNewPath;
	@FXML
	private TextField newPathName;
	@FXML
	private TextField newPathDifficulty;
	@FXML
	private TextField newPathDistance;
	@FXML
	private Button updateExistingPath;
	@FXML
	private TextField updatedPathDifficulty;
	@FXML
	private TextField updatedPathDistance;
	@FXML
	private TextField updatedPathName;
	@FXML
	private TextField oldPathName;
	@FXML
	private Button deleteExistingPath;
	@FXML
	private TextField pathToDelete;

	// Event Listener on Button[#addNewPath].onAction
	@FXML
	public void AddPath(ActionEvent event) {
		// TODO Autogenerated
	  try {
	    ExtraFeaturesController.addClimbingPath(newPathName.getText(), Integer.parseInt(newPathDistance.getText()), newPathDifficulty.getText());
	  }catch(Exception e) {
	    ViewUtils.showError(e.getMessage());
	  }
	}
	// Event Listener on Button[#updateExistingPath].onAction
	@FXML
	public void UpdatePath(ActionEvent event) {
		// TODO Autogenerated
	   try {
	        ExtraFeaturesController.updateClimbingPath(oldPathName.getText(),updatedPathName.getText(), Integer.parseInt(updatedPathDistance.getText()), updatedPathDifficulty.getText());
	      }catch(Exception e) {
	        ViewUtils.showError(e.getMessage());
	      }
	    }
	
	// Event Listener on Button[#deleteExistingPath].onAction
	@FXML
	public void deletePath(ActionEvent event) {
		// TODO Autogenerated
	   try {
         ExtraFeaturesController.deleteClimbingPath(pathToDelete.getText());
       }catch(Exception e) {
         ViewUtils.showError(e.getMessage());
       }
     
	}
}
