package ca.mcgill.ecse.climbsafe.javafx.fxml.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.ComboBox;

import javafx.scene.control.Tab;

import javafx.scene.input.MouseEvent;

import javafx.event.Event;

public class ClimbingPathOperationsController {
	@FXML
	private Tab addPathTab;
	@FXML
	private Button addNewPath;
	@FXML
	private TextField newPathDistance;
	@FXML
	private TextField addBundleName;
	@FXML
	private ComboBox addDifficultyCombo;
	@FXML
	private ListView pathList;
	@FXML
	private ListView pathDistList;
	@FXML
	private ListView pathDiffList;
	@FXML
	private Tab UpdatePathTab;
	@FXML
	private Button updateExistingPath;
	@FXML
	private TextField updatedPathDistance;
	@FXML
	private TextField updatedPathName;
	@FXML
	private TextField oldPathName;
	@FXML
	private ComboBox newDifficultyCombo;
	@FXML
	private ListView newPathList;
	@FXML
	private ListView newDistList;
	@FXML
	private ListView newDiffList;
	@FXML
	private Tab DeletePathTab;
	@FXML
	private Button deleteExistingPath;
	@FXML
	private ListView rmPathList;
	@FXML
	private ListView rmDistList;
	@FXML
	private ListView rmDiffList;

	// Event Listener on Tab[#addPathTab].onSelectionChanged
	@FXML
	public void RefreshSystemPaths1(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addNewPath].onAction
	@FXML
	public void AddPath(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Tab[#UpdatePathTab].onSelectionChanged
	@FXML
	public void RefreshSystemPaths2(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateExistingPath].onAction
	@FXML
	public void UpdatePath(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Tab[#DeletePathTab].onSelectionChanged
	@FXML
	public void RefreshSystemPaths3(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteExistingPath].onAction
	@FXML
	public void deletePath(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#rmPathList].onMouseClicked
	@FXML
	public void selectedPath(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#rmDistList].onMouseClicked
	@FXML
	public void selectedDistance(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#rmDiffList].onMouseClicked
	@FXML
	public void selectedDifficulty(MouseEvent event) {
		// TODO Autogenerated
	}
}
