package ca.mcgill.ecse.climbsafe.javafx.fxml.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet4Controller;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet6Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Tab;

import javafx.event.Event;

public class EquipmentOperationsController {
	@FXML
	private Tab EqTab1;
	@FXML
	private TextField addEqWeight;
	@FXML
	private Button addEquipmentButton;
	@FXML
	private TextField addEqName;
	@FXML
	private TextField addEqPrice;
	@FXML
	private ListView SystemEquipment;
	@FXML
	private Tab EqTab2;
	@FXML
	private TextField updtEqNewWeight;
	@FXML
	private Button updateEquipmentButton;
	@FXML
	private TextField updtEqNewName;
	@FXML
	private TextField updtEqNewPrice;
	@FXML
	private ListView SystemEquipment1;
	@FXML
	private TextField updtEqName;
	@FXML
	private Tab EqTab3;
	@FXML
	private Button deleteEquipmentButton;
	@FXML
	private TextField rmEquipmentName;
	@FXML
	private ListView equipmentList;

	// Event Listener on Tab[#EqTab1].onSelectionChanged
	@FXML
	public void RefreshSystemEquipment(Event event) {
		// TODO 
	}
	// Event Listener on Button[#addEquipmentButton].onAction
	@FXML
	public void addEquipmentAction(ActionEvent event) {
	  try {
	    ClimbSafeFeatureSet4Controller.addEquipment(addEqName.getText(), Integer.parseInt(addEqWeight.getText()), Integer.parseInt(addEqPrice.getText()));
      } catch (Exception e) {
        ViewUtils.showError(e.getMessage());
      }
	}
	// Event Listener on Tab[#EqTab2].onSelectionChanged
	@FXML
	public void RefreshSystemEquipment2(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateEquipmentButton].onAction
	@FXML
	public void updateEquipmentAction(ActionEvent event) {
		try {
          ClimbSafeFeatureSet4Controller.updateEquipment(updtEqName.getText(), updtEqNewName.getText(), Integer.parseInt(updtEqNewWeight.getText()), Integer.parseInt(updtEqNewPrice.getText()));
        } catch (Exception e) {
          ViewUtils.showError(e.getMessage());
        }
	}
	// Event Listener on Tab[#EqTab3].onSelectionChanged
	@FXML
	public void RefreshSystemEquipment3(Event event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteEquipmentButton].onAction
	@FXML
	public void deleteEquipmentAction(ActionEvent event) {
		try {
          ClimbSafeFeatureSet6Controller.deleteEquipment(rmEquipmentName.getText());
        } catch (Exception e) {
          ViewUtils.showError(e.getMessage());
        }
	}
}
