package ca.mcgill.ecse.climbsafe.javafx.fxml.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import java.util.ArrayList;
import ca.mcgill.ecse.climbsafe.controller.ExtraFeaturesController;
import ca.mcgill.ecse.climbsafe.controller.InvalidInputException;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class ReviewOperationsController {
	@FXML
	private Button submitTripReview;
	@FXML
	private TextField memberEmailTripReview;
	@FXML
	private TextField commentTripReview;

	
	   private String[] rating= {"VeryPoor", "Poor", "Neutral", "Good", "VeryGood"};

	@FXML

	
	private ComboBox ratingTripReview = new ComboBox<String>(FXCollections.observableArrayList(rating));

	
	// Event Listener on Button[#submitTripReview].onAction
	@FXML
	public void submitReviewAction(ActionEvent event) throws InvalidInputException {
		// TODO Autogenerated
	  String rating=(String) ratingTripReview.getValue();
	  
	  try {
	    ExtraFeaturesController.rateClimb(memberEmailTripReview.getText(), rating, commentTripReview.getText());; // change
	  } catch(Exception e) {
	    ViewUtils.showError("Your email does not exist in the system");
	  }
	  
	  ViewUtils.showSuccess("Your review was successfully submitted");
	}
}
